const BAD_REQUEST_STATUS_CODE = 400;

const NOT_FOUND_STATUS_CODE = 404;

const SERVER_ERROR_STATUS_CODE = 500;

module.exports = {
  BAD_REQUEST_STATUS_CODE,
  NOT_FOUND_STATUS_CODE,
  SERVER_ERROR_STATUS_CODE,
};
