const BAD_REQUEST_STATUS_CODE = 400;

const NOT_FOUND_STATUS_CODE = 404;

const SERVER_ERROR_STATUS_CODE = 500;

const CONFLICT_STATUS_CODE = 409;

const UNAUTHORIZED_STATUS = 401;

const FORBIDDEN = 403;

module.exports = {
  BAD_REQUEST_STATUS_CODE,
  NOT_FOUND_STATUS_CODE,
  SERVER_ERROR_STATUS_CODE,
  CONFLICT_STATUS_CODE,
  UNAUTHORIZED_STATUS,
  FORBIDDEN,
};
